---@class IPicker
---@field entries fun(callback: fun(document_path: string),id: string, entries: EntryModel[])
---@field registries fun(callback: fun(document_slug: string), registries: RegistryModel[])
