---@meta
--- Output port for fetching documentation content. Implemented by infrastructure/external/requests/documentations_request.lua.
---@class DocumentationsProviderPort
---@field find fun(slug: string): table<string,string>[] | nil
---@field find_async fun(slug: string, on_success: fun(result: table<string,string>[] | nil))
