---@meta
--- Output port for fetching the devdocs registry list. Implemented by infrastructure/external/requests/registries_request.lua.
---@class RegistriesProviderPort
---@field list fun(): RegistryModel[]
