---@meta
--- Output port for fetching the devdocs registry list. Implemented by infrastructure/external/providers/registries_provider.lua.
---@class RegistriesProviderPort
---@field list fun(): RegistryModel[]
