---@meta
--- Output port for fetching individual document pages. Implemented by infrastructure/external/providers/documents_provider.lua.
---@class DocumentsProviderPort
---@field get fun(slug: string, document_path: string): string
