---@meta
--- Output port for fetching individual document pages. Implemented by infrastructure/requests/documents_request.lua.
---@class DocumentsProviderPort
---@field get fun(slug: string, document_path: string): string
