---@meta
--- Output port for persisting and reading entry indices. Implemented by infrastructure/repositories/entries_repository.lua.
---@class EntriesPersistencePort
---@field save fun(entries: EntryModel[], name: string)
---@field find fun(name: string): EntryModel[] | nil
