---@meta
--- Output port for persisting the devdocs registry. Implemented by infrastructure/repositories/registeries_repository.lua.
---@class RegistriesRepositoryPort
---@field save fun(registry: RegistryModel[])
---@field list fun(): RegistryModel[] | nil
