---@class RegistryModel
---@field name string
---@field alias string
---@field attribution string
---@field db_size number
---@field links table<string,string>
---@field mtime number
---@field release string
---@field slug string
---@field type string
---@field version string
